'use strict';
const assert=require('node:assert/strict'), fs=require('fs'), vm=require('vm');
const specialty=require('../news-app-2-specialty.js');
const context={window:{}};vm.runInNewContext(fs.readFileSync('lexicon-tab.js','utf8'),context);
const snap=context.window.WRNLexicon184.snapshot(), books=JSON.parse(fs.readFileSync('library-feed.json')), paths=JSON.parse(fs.readFileSync('learning-paths.json'));
const linked=specialty.learningPathsForCatalog(paths,books,snap.terms);
assert.equal(linked.length,4); assert.equal(linked.reduce((n,p)=>n+p.entries.length,0),33);
const withdrawn=books.map(b=>b.id===paths.paths[0].entries[0].bookId?{...b,status:'withdrawn'}:b);
assert.equal(specialty.learningPathsForCatalog(paths,withdrawn,snap.terms).flatMap(p=>p.entries).length,32);
const bad=structuredClone(paths); bad.paths[0].entries[0].originalUrl='https://other.example/book';bad.paths[0].entries[1].termIds=['unknown'];
assert.equal(specialty.learningPathsForCatalog(bad,books,snap.terms).flatMap(p=>p.entries).length,31);
const digital=linked.find(p=>p.id==='digital-commons-and-self-organisation');
assert.equal(digital.entries.length,3);
const revokedTerms=snap.terms.map(t=>t.id==='digital-commons'?{...t,status:'revoked'}:t);
assert.equal(specialty.learningPathsForCatalog(paths,books,revokedTerms).find(p=>p.id===digital.id).entries.length,1,'revoking the digital commons term hides both bound comparisons');
assert.equal(snap.terms.filter(t=>t.revision?.version==='knowledge-expansion-2').length,19);
console.log('4 learning paths, 33 bound relationships, book/term revocations and invalid bindings passed; 19 DE/EN revisions.');
